#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#
#

set -e

printf "⏳ Loading context data "

#
# Create four Home Entities in various locations across Berlin
#
curl -s -o /dev/null -X POST \
  'http://192.168.0.150:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -g -d '{
  "actionType": "append",
  "entities": [
  	{
  		"id":"urn:ngsi-ld:Home:001",
  		"type":"Home",
  		"address":{"type":"PostalAddress","value":{"streetAddress":"Bornholmer Straße 65","addressRegion":"Berlin","addressLocality":"Prenzlauer Berg","postalCode":"10439"}},
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.3986,52.5547]}},
  		"name":{"type":"Text","value":"Bösebrücke Einkauf"}
  	}
  ]
}'



echo -e " \033[1;32mdone\033[0m"

